theme = 'hugo-theme-relearn'
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Java Curriculum'

[params]
themeVariant = 'relearn-light'

[markup.goldmark.renderer]
unsafe = true

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']
